### ISSUE TITLE
You

### ISSUE THREAD

**Issue by kacperleague9** [Refrac/Sophos#1]
Plugin changes some words on chat to you
like dlugo

**Comment by Refrac** [comment]
I will look into this tho for now i suggest disabling AutoCorrect in the config file

**Comment by Refrac** [comment]
Alright i know what the real issue is AutoDot seems to be messing with it as well so whenever a dot is added on to the end of an AutoCorrectable word it won't AutoCorrect it

**Comment by Refrac** [comment]
This issue has been fixed as of 2.2.4/7.1 Hotfix https://www.spigotmc.org/resources/sophos-chat-protection-1-7-10-1-15-2.55372/update?update=329622
